language: node_js
node_js:
  - 8
  - 6
  - 4
services:
  - mongodb
script: "npm install --no-save mongoose@5 && npm run-script test-travis"
after_script: "npm install --no-save coveralls@3.0.0 && cat ./coverage/lcov.info | coveralls"
